read/write mode
dataiku/dss-plugin-box.com pull request #3
Opened 2019-09-12 13:13 UTC by alexbourret

This PR takes priority since the customer needs write capabilities from day one.

2019-09-12 13:37 UTC, apichery requested changes

2019-09-25 10:07 UTC, du-phan requested changes

2019-09-30 02:02 UTC, JoachimZ reviewed
Purely formal comments, did not really look at the code for now :)

2019-11-19 01:16 UTC, JoachimZ requested changes
Could you move the doc and apply the plugin dev kit (supportLevel: NOT_SUPPORTED for now)

2019-11-22 23:20 UTC, merged